http:
  middlewares:
    secureHeaders:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.localhost`)"
      service: api@internal
      middlewares:
        - secureHeaders
